# Honda Odyssey Inventory Tool

In [4]:
from main import get_honda_odyssey_inventory
import pandas as pd

# Configuration
ZIP_CODE = "78723"  # Change this to your desired zip code
MAX_DEALERS = 100    # Maximum number of dealers to search

# my current location
lat, lng = 30.2961283,-97.7061865 # Austin

print("Honda Odyssey Inventory Tool")
print("=" * 40)
print(f"Searching for Honda Odyssey vehicles near zip code: {ZIP_CODE}")
print(f"Maximum dealers: {MAX_DEALERS}")
print()
print("✅ Ready to fetch data using cookie from .cookie file")
print("Note: Make sure you have created a .cookie file with your cookie string")
print("See README.md for instructions on how to get the cookie from browser dev tools")

Honda Odyssey Inventory Tool
========================================
Searching for Honda Odyssey vehicles near zip code: 78723
Maximum dealers: 100

✅ Ready to fetch data using cookie from .cookie file
Note: Make sure you have created a .cookie file with your cookie string
See README.md for instructions on how to get the cookie from browser dev tools

In [5]:
df = get_honda_odyssey_inventory(ZIP_CODE, MAX_DEALERS)

In [6]:
print("found ", len(df), " vehicles")
df.head(2)

found  104  vehicles

,dealer,address1,city,state,postal,phone,lat,lon,retail_url,trim,inv_type,color,vin,price
0,First Texas Honda,,Austin,TX,787578045,5124582511,30.367687,-97.739082,,EX-L,,Modern Steel Metallic,5FNRL6H6XSB089980,"$42,220"
1,First Texas Honda,,Austin,TX,787578045,5124582511,30.367687,-97.739082,,Sport-L,,Platinum White Pearl,5FNRL6H75SB077082,"$43,825"

In [4]:
from util import harvesine, driving_time

def distance_to_dealer_df(df, lat, lng):
    df['driving_distance'] = df.apply(lambda x: harvesine(x['lat'], x['lon'], lat, lng), axis=1)
    df['driving_time_hr'] = df.apply(lambda x: driving_time(x['lat'], x['lon'], lat, lng), axis=1)

In [5]:
# Display the results
distance_to_dealer_df(df, lat, lng)
df.head(10)

,dealer,address1,city,state,postal,phone,lat,lon,retail_url,trim,inv_type,color,vin,price,driving_distance,driving_time_hr
0,First Texas Honda,,Austin,TX,787578045,5124582511,30.367687,-97.739082,,EX-L,,Modern Steel Metallic,5FNRL6H6XSB089980,"$42,220",5.319252,0.088654
1,First Texas Honda,,Austin,TX,787578045,5124582511,30.367687,-97.739082,,Sport-L,,Platinum White Pearl,5FNRL6H75SB077082,"$43,825",5.319252,0.088654
2,First Texas Honda,,Austin,TX,787578045,5124582511,30.367687,-97.739082,,Sport-L,,Platinum White Pearl,5FNRL6H79SB084052,"$43,825",5.319252,0.088654
3,Gunn Honda,,San Antonio,TX,782493200,8003246632,29.579609,-98.597069,,Sport-L,,Crystal Black Pearl,5FNRL6H78SB083197,"$43,370",72.774813,1.212914
4,Gillman Honda,,Houston,TX,770992844,7137764800,29.664400,-95.556381,,Elite,,Solar Silver Metallic,5FNRL6H91SB060622,"$51,180",135.863220,2.264387
5,Russell & Smith Honda,,Houston,TX,770541308,7133632220,29.678368,-95.422737,,Touring,,Crystal Black Pearl,5FNRL6H84SB061366,"$46,910",143.160459,2.386008
6,Russell & Smith Honda,,Houston,TX,770541308,7133632220,29.678368,-95.422737,,Touring,,Platinum White Pearl,5FNRL6H81SB065696,"$47,365",143.160459,2.386008
7,Russell & Smith Honda,,Houston,TX,770541308,7133632220,29.678368,-95.422737,,Touring,,Platinum White Pearl,5FNRL6H83SB082094,"$47,365",143.160459,2.386008
8,Russell & Smith Honda,,Houston,TX,770541308,7133632220,29.678368,-95.422737,,Elite,,Platinum White Pearl,5FNRL6H90SB084152,"$51,635",143.160459,2.386008
9,Russell & Smith Honda,,Houston,TX,770541308,7133632220,29.678368,-95.422737,,Elite,,Platinum White Pearl,5FNRL6H97SB086481,"$51,635",143.160459,2.386008

In [26]:
df.phone.unique()

array([''], dtype=object)